Build on Fedora 25:
  stage: build
  image: "fedora:25"
  before_script:
    - yum -y install gcc-c++ cmake make
  script:
    - mkdir build && cd build
    - cmake ..
    - make

Test:
  stage: test
  image: "fedora:25"
  script:
    - echo "test passed"
    