# enable the 'trusty beta' VM to access a modern gcc
dist: trusty
sudo: required

# setup for C++
language: c++
compiler:
  - clang
  - gcc

# the actual build and test process
script:
  - mkdir build
  - cd build
  - cmake .. && make
