# enable the 'trusty beta' VM to access a modern gcc
dist: trusty
sudo: required

# setup for C++
language: c++
compiler:
  - clang
  - gcc

# install dependencies (for ODIM)
addons:
  apt:
    packages:
      - libhdf5-dev

install:
  - pwd
  - ls
  - git clone https://github.com/bom-radar/odim_h5.git
  - pushd odim_h5
  - pwd
  - ls
  - mkdir build && pushd build
  - cmake .. && make && sudo make install
  - pwd
  - ls
  - popd
  - pwd
  - ls

# the actual build and test process
script:
  - pwd
  - ls
  - mkdir build
  - cd build
  - cmake .. && make
